/**
 * @description Office
 * @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
 * @note        Auto-generated by: https://github.com/pmndrs/gltfjsx
 * @note        Command: npx gltfjsx@6.5.3 -t public/model/office.glb
 */
import {useRef} from 'react'
import * as THREE from 'three'
import {useFrame} from '@react-three/fiber'
import * as React from 'react'
import {Float, useGLTF, useScroll} from '@react-three/drei'
import type {GLTFResult} from '../../types'
import {Mathy} from '../../utils/Mathy.ts'

const GROUP_START_Y = -1
const GROUP_END_Y = -6

const LIBRARY_START_Z = -6
const LIBRARY_END_Z = -2.23

const ATTIC_START_Z = -6
const ATTIC_END_Z = -2.199
const ATTIC_START_X = -6
const ATTIC_END_X = -1.97

export const Office = (props: React.JSX.IntrinsicElements['group']) => {
  const groupRef = useRef<THREE.Mesh | null>(null)
  const officeRef = useRef<THREE.Mesh | null>(null)
  const libraryRef = useRef<THREE.Mesh | null>(null)
  const atticRef = useRef<THREE.Mesh | null>(null)

  const scroll = useScroll()

  useFrame(() => {
    if (
      !groupRef.current ||
      !officeRef.current ||
      !libraryRef.current ||
      !atticRef.current
    )
      return

    const tGroup = scroll.range(0, 2 / 3)
    groupRef.current.position.y = Mathy.lerp(GROUP_START_Y, GROUP_END_Y, tGroup)

    const tLibrary = scroll.range(0, 1 / 3)
    libraryRef.current.position.z = Mathy.lerp(
      LIBRARY_START_Z,
      LIBRARY_END_Z,
      tLibrary,
    )
    libraryRef.current.rotation.y = Mathy.lerp(0, 2 * Math.PI, tLibrary)

    const tAttic = scroll.range(1 / 3, 1 / 3)
    atticRef.current.position.x = Mathy.lerp(ATTIC_START_X, ATTIC_END_X, tAttic)
    atticRef.current.position.z = Mathy.lerp(ATTIC_START_Z, ATTIC_END_Z, tAttic)
    atticRef.current.rotation.y = Mathy.lerp(0, 2 * Math.PI, tAttic)
  })

  const {nodes, materials} = useGLTF(
    '/r3f-scroll-animation/model/office.glb',
  ) as unknown as GLTFResult
  return (
    <Float>
      <group
        {...props}
        dispose={null}
        ref={groupRef}
        position-y={GROUP_START_Y}
      >
        <mesh
          geometry={nodes['01_office'].geometry}
          material={materials['01']}
          ref={officeRef}
        />
        <mesh
          geometry={nodes['02_library'].geometry}
          material={materials['02']}
          position={[0, 2.114, LIBRARY_END_Z]}
          ref={libraryRef}
        />
        <mesh
          geometry={nodes['03_attic'].geometry}
          material={materials['03']}
          position={[ATTIC_END_X, 4.227, ATTIC_END_Z]}
          ref={atticRef}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('/r3f-scroll-animation/model/office.glb')
