/**
 * @description Office
 * @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
 * @note        Auto-generated by: https://github.com/pmndrs/gltfjsx
 * @note        Command: npx gltfjsx@6.5.3 -t public/model/office.glb
 */
import * as React from 'react'
import {useGLTF} from '@react-three/drei'
import type {GLTFResult} from '../../types'

export const Office = (props: React.JSX.IntrinsicElements['group']) => {
  const {nodes, materials} = useGLTF(
    '/r3f-scroll-animation/model/office.glb',
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['01_office'].geometry} material={materials['01']} />
      <mesh
        geometry={nodes['02_library'].geometry}
        material={materials['02']}
        position={[0, 2.114, -2.23]}
      />
      <mesh
        geometry={nodes['03_attic'].geometry}
        material={materials['03']}
        position={[-1.97, 4.227, -2.199]}
      />
    </group>
  )
}

useGLTF.preload('/r3f-scroll-animation/model/office.glb')
